code --install-extension CraigMaslowski.erb
code --install-extension cazoobi.solis
code --install-extension aaron-bond.better-comments
code --install-extension aeschli.vscode-css-formatter
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension bierner.github-markdown-preview
code --install-extension bierner.lit-html
code --install-extension bierner.markdown-checkbox
code --install-extension bierner.markdown-emoji
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bierner.markdown-yaml-preamble
code --install-extension bradlc.vscode-tailwindcss
code --install-extension bung87.rails
code --install-extension bung87.vscode-gemfile
code --install-extension castwide.solargraph
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension cssho.vscode-svgviewer
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension develiteio.api-blueprint-viewer
code --install-extension donjayamanne.githistory
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.tslint
code --install-extension Equinusocio.vsc-material-theme
code --install-extension erd0s.terraform-autocomplete
code --install-extension esbenp.prettier-vscode
code --install-extension faustinoaq.crystal-lang
code --install-extension felixrieseberg.vsc-travis-ci-status
code --install-extension formulahendry.auto-rename-tag
code --install-extension ginfuru.ginfuru-vscode-jekyll-syntax
code --install-extension ginfuru.vscode-jekyll-snippets
code --install-extension GitHub.vscode-pull-request-github
code --install-extension GrapeCity.gc-excelviewer
code --install-extension Gruntfuggly.todo-tree
code --install-extension HookyQR.beautify
code --install-extension JakeBecker.elixir-ls
code --install-extension karunamurti.haml
code --install-extension KnisterPeter.vscode-github
code --install-extension luggage66.VBScript
code --install-extension mariomatheu.syntax-project-pbxproj
code --install-extension mathiasfrohlich.Kotlin
code --install-extension mechatroner.rainbow-csv
code --install-extension mhcpnl.xcodestrings
code --install-extension mikestead.dotenv
code --install-extension misogi.ruby-rubocop
code --install-extension mjmcloug.vscode-elixir
code --install-extension mkxml.vscode-filesize
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension MS-CEINTL.vscode-language-pack-es
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.sublime-keybindings
code --install-extension ms-vscode.wordcount
code --install-extension msjsdiag.vscode-react-native
code --install-extension naumovs.color-highlight
code --install-extension nestalk.preview-control-characters
code --install-extension oderwat.indent-rainbow
code --install-extension pepri.subtitles-editor
code --install-extension pnp.polacode
code --install-extension pranaygp.vscode-css-peek
code --install-extension rebornix.ruby
code --install-extension redhat.java
code --install-extension rust-lang.rust
code --install-extension shardulm94.trailing-spaces
code --install-extension sianglim.slim
code --install-extension SimonSiefke.svg-preview
code --install-extension steoates.autoimport
code --install-extension tomoki1207.pdf
code --install-extension vincaslt.highlight-matching-tag
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vncz.vscode-apielements
code --install-extension vortizhe.simple-ruby-erb
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wayou.vscode-todo-highlight
code --install-extension wholroyd.HCL
code --install-extension wingrunr21.vscode-ruby
code --install-extension wix.vscode-import-cost
code --install-extension wmaurer.change-case
code --install-extension xabikos.ReactSnippets
code --install-extension Yummygum.city-lights-icon-vsc
code --install-extension yummygum.city-lights-theme
code --install-extension yzane.markdown-pdf
code --install-extension zhouronghui.propertylist
code --install-extension Zignd.html-css-class-completion
